// app/layout.tsx
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import "./globals.css";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import SignIn from "@/components/SignIn";
import QueryProviders from "@/features/shared/provider/Tanstack";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Prep Station",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <QueryProviders>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <SignedOut>
                <SignIn />
              </SignedOut>
              <SignedIn>
                <main>
                  {children}
                </main>
              </SignedIn>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </QueryProviders>
  );
}